@startuml

title Components - Component Diagram

 node "Unity" {
  [Client]
  }
  
   node "Kinect" {
  [KinectSDK]
  }
  
  node "Server" {
  [DataBase]
  [Php app]
  }
  
  [Client] --> [KinectSDK]: request

  [KinectSDK] --> [Client] : respone

  [Client] --> [Php app] : request

  [Php app] --> [Client] : respone

  [DataBase] --> [Php app] : respone

  [Php app] --> [DataBase] : request

@enduml
